#!/bin/bash 
#shopt -s extglob

echo "err" >&2

exit 1
#NSPATH="PBL"
#SPATH="LBP"
#foo () {
#PATH=""$1"PATH"
#echo ${!PATH}
#}

#foo "NS"
#echo
#foo "S"

#clean_var() {
#	local RESULT=$1
#	RESULT="${RESULT//[$'\n\t\r\f']/}"
#	RESULT="${RESULT#"${RESULT%%[![:space:]]*}"}"
#	RESULT="${RESULT%"${RESULT##*[![:space:]]}"}"
#	echo -n "$RESULT"
#}
#if [ ! -e foo.csv ]; then
#  echo DATETIME,BODY,AGE,LOCATION,ID,ADTYPE > ./foo.csv
#fi
#for AD in ./page.html ./page2.html; do
#  WRITEBODY=0
#  while read LINE; do
#    grep -q "</div>" <(echo "$LINE")
#	if [ $? -eq 0 -a "$WRITEBODY" -eq 1 ]; then
#		break
#	fi
#	if [ "$WRITEBODY" -eq 1 ]; then
#		#BODY="${BODY}""${LINE}"$'\n'
#	fi
#	grep -q "<div class=\"postingBody\">" <(echo "$LINE")
#	if [ $? -eq 0 ]; then
#		WRITEBODY=1
#	fi
 # done < "$AD"
# BODY="${BODY//+([$'\n\r\t']|<br>)/ }"
#  DATETIME=`grep -o "[[:upper:]][[:lower:]]\+, [[:upper:]][[:lower:]]\+ [0-9]\+, [0-9]\{4\} [0-9]\+:[0-9]\{2\} [APM]*" "$AD"`
#  AGE=`grep -oP "(?<=Poster's age: )[0-9]*"  "$AD"`
#  LOCATION=`pcregrep -oM "(?<=Location:)\W*?.*\W*?(?=</div)" "$AD"`
#  LOCATION=`clean_var "$LOCATION"`
#  echo '1)='"$LOCATION"=
#  ID=`grep -oP '(?<=Post ID: )[0-9]*' "$AD"`
#  OTHERADS=`grep -v "http://albuquerque.backpage.com/MaleEscorts/muscular-stud-available-sexy-face-nice-body-great-skills-incall/7799581" <(grep -o "http://[a-z]\+\./backpage\.com/[a-z]*/[a-z\-]\+/[0-9]\+" "$AD")`
#  if [ ! -d conte/"$ID" ]; then
#     mkdir -p conte/"$ID"/img
#  fi
#  NSIPATH=conte/"$ID"/imgs
#			
#  echo "$DATETIME" > conte/"$ID"/datetime.txt
#  echo "$BODY"	 > conte/"$ID"/body.txt
#  echo "$AGE"	 > conte/"$ID"/age.txt
#  echo "$LOCATION" > conte/"$ID"/location.txt
#  if [ ! -z "$OTHERADS" ]; then
#	echo "$OTHERADS" > conte/"$ID"/otheradurls.txt
#  fi

#  IMGURL=`paste -sd, <(grep -Po '(?<=(img src="))[^ ]*(?=")' "$AD")`
#  if [ ! -z "$IMGURL" ]; then
#    cd "$NSIPATH"
#    for I in 1 2; do
#      touch img_"$I".jpg
#    done
#  fi
#  echo "\""$DATETIME"\",\""$BODY"\","$AGE",\""$LOCATION"\","$ID",0" >> ./foo.csv
#  BODY=;DATETIME=;AGE=;LOCATION=;ID=;OTHERADS=;IMGURL=;
#done

#echo "\<div\ class=\"postingBody\"\>[\n\s.]*[[:^alnum:][:alnum:]]*?(?!\<\/div\>)"; echo

#pcregrep -Mo "\<div\ class=\"postingBody\"\>[\n\s.]*[[:^alnum:][:alnum:]]*?(?!\<\/div\>)" ./page.html
#echo --------------------------------------------
#pcregrep -M "\<div\ class=\"postingBody\"\>[\n\s.]*[[:^alnum:][:alnum:]]*?(?!\<\/div\>)" ./page.html

#echo exit status $?; echo ===========================================================; echo


#echo "metaInfo for poster age"
#grep metaInfo <./page.html | grep -io \>[[:print:]]*\<
# cat file | tr -d '\n' | tr -s ' ' | grep -o \<div\ class=\"postingBody\"\>[.[:space:]]*.*
#echo exit status $?; echo ===========================================================; echo
#WRITE=0
#while read LINE; do
# grep -q "</div>" <(echo "$LINE")
# if [ $? -eq 0 ]; then
#  WRITE=0
# fi
#
# if [ "$WRITE" -eq 1 ]; then
#     BODY="${BODY}""${LINE}"$'\n'
# fi

# grep -q "<div class=\"postingBody\">" <(echo "$LINE")
# if [ $? -eq 0 ]; then
#  WRITE=1
# fi
#done < ./page.html 
#echo "${BODY//+([$'\t\n\r']|<br>)}"


#IMG=`paste -sd, <(grep -Po '(?<=(img src="))[^ ]*(?=")' page.html)`
#curl -O "{"$IMG"}"
#exit 
#if [ -e postingBody.txt -a ! -z postingBody.txt ]; then
# exit 0
#else
# exit 1
#fi
#exit
